name: "phpcs check"

on: 
  push:
    branches:
      - dev

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important!
      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version
      - name: Run PHP_CodeSniffer 
        run: php phpcs.phar -s -p --colors --extensions=php --standard=.github/rules.xml .